server:
  context-path: /alert
  port: 9074

mybatis:
  config-location: 'classpath:mybatis.xml'
  mapper-locations: 'classpath:mybatis/*.xml'

qywx:
  agent-id: '1000025'
  secret: '9ADDEg3LhngTOzqtjs1VuEgOmtldRiTz4nksYdH2l5k'
  corp-id: 'wxad8b8474f08dc086'

tapd:
  workspace-id: ''
  reporter: ''

spring:
  kafka:
    bootstrap-servers: kafka1.skye.dafy.com:9092,kafka2.skye.dafy.com:9092,kafka3.skye.dafy.com:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432

alert:
  mq:
    topic: 'skye.alert'