
log:
  file: /opt/hive/oozie.log
  pattern: "%-20(%d{HH:mm:ss.SSS} [%thread]) %-5level [%X{braveTraceId}] %logger{80}:%line - %msg%n"
  fileNamePattern: "/oozie.%d{yyyy-MM-dd}.log"


action:
    regionImport: com.dafy.skye.hadhoop.workflow.action.RegionImport
    storeImport: com.dafy.skye.hadhoop.workflow.action.StoreImport
    customerImport: com.dafy.skye.hadhoop.workflow.action.FCustomerImport
    loanImport: com.dafy.skye.hadhoop.workflow.action.FLoanOrderImport
    repayImport: com.dafy.skye.hadhoop.workflow.action.FRepayOrderImport
    customerLoanImport: com.dafy.skye.hadhoop.workflow.action.SCustomerLoanImport

com.dafy.skye.hadhoop.workflow.action.RegionImport:
  excludeNames:
    - "县"


hdfs.dir: hdfs://cdh2.dafy.com:8020/user/root

hive:
    connectUrl: "jdbc:hive2://cdh2.dafy.com:10000/sevend"
    user: root
    password: root
    driver.class: "org.apache.hive.jdbc.HiveDriver"

mysql:
    driver.class: "com.mysql.jdbc.Driver"
    connectUrl: "jdbc:mysql://rdsc14z37q7i8pq2m79fo.mysql.rds.aliyuncs.com:3306/sevend?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&tinyInt1isBit=false"
    user: dafy
    password: dafy1024
    #connectUrl: "jdbc:mysql://10.8.14.30:3305/sevend?useUnicode=true&characterEncoding=utf8&autoReconnect=true"
    #user: root
    #password: 4r3e2w1q
