zipkin:
  self-tracing:
    # Set to true to enable self-tracing.
    enabled: ${SELF_TRACING_ENABLED:false}
    # percentage to self-traces to retain
    sample-rate: ${SELF_TRACING_SAMPLE_RATE:1.0}
    # Interval in seconds to flush self-tracing data to storage.
    flush-interval: ${SELF_TRACING_FLUSH_INTERVAL:1}
  collector:
    # percentage to traces to retain
    sample-rate: ${COLLECTOR_SAMPLE_RATE:1.0}
    kafka:
      # ZooKeeper host string, comma-separated host:port value.
      bootstrap-servers: ${KAFKA_SERVER:kafka1.skye.dafy.com:9092,kafka2.skye.dafy.com:9092,kafka3.skye.dafy.com:9092}
      # Name of topic to poll for spans
      topic: ${KAFKA_TOPIC:zipkin}
      # Consumer group this process is consuming on behalf of.
      group-id: ${KAFKA_GROUP_ID:zipkin-dev1}
      # Count of consumer threads consuming the topic
      streams: ${KAFKA_STREAMS:1}
      # Maximum size of a message containing spans in bytes
      max-message-size: ${KAFKA_MAX_MESSAGE_SIZE:1048576}

    scribe:
      enabled: ${SCRIBE_ENABLED:true}
      category: zipkin
      port: ${COLLECTOR_PORT:19410}
  query:
    # 7 days in millis
    lookback: ${QUERY_LOOKBACK:604800000}
    # The Cache-Control max-age (seconds) for /api/v1/services and /api/v1/spans
    names-max-age: 300
    # CORS allowed-origins.
    allowed-origins: "*"
  storage:
    strict-trace-id: ${STRICT_TRACE_ID:true}
    type: ${STORAGE_TYPE:elasticsearch}
    elasticsearch:
      # host is left unset intentionally, to defer the decision
      hosts: ${ES_HOSTS:http://127.0.0.1:9200}
      pipeline: ${ES_PIPELINE:}
      max-requests: ${ES_MAX_REQUESTS:64}
      index: ${ES_INDEX:zipkin}
      date-separator: ${ES_DATE_SEPARATOR:-}
      index-shards: ${ES_INDEX_SHARDS:3}
      index-replicas: ${ES_INDEX_REPLICAS:1}
      username: ${ES_USERNAME:}
      password: ${ES_PASSWORD:}
      index-template: zipkin-es-template.json
  ui:
    ## Values below here are mapped to ZipkinUiProperties, served as /config.json
    # Default limit for Find Traces
    query-limit: 10
    # The value here becomes a label in the top-right corner
    environment: TEST
    # Default duration to look back when finding traces.
    # Affects the "Start time" element in the UI. 1 hour in millis
    default-lookback: 3600000
    # Which sites this Zipkin UI covers. Regex syntax. (e.g. http:\/\/example.com\/.*)
    # Multiple sites can be specified, e.g.
    # - .*example1.com
    # - .*example2.com
    # Default is "match all websites"
    instrumented: .*

druid:
    zk:
      host: druid-zk1.dafy.com:2181
      path: /druid/discovery/druid:broker
      namespace: druid-broker-service-discovery
    kafka:
      # Name of topic to poll for spans
      topic: ${KAFKA_TOPIC:zipkin}
      #是否自动ack
      properties:
          #kafka 地址
          group.id: druid
          bootstrap.servers: ${KAFKA_SERVER:kafka1.skye.dafy.com:9092,kafka2.skye.dafy.com:9092,kafka3.skye.dafy.com:9092}
          max.poll.records: 100
          max.poll.interval.ms: 60000
          #是否自动ack
          enable.auto.commit: false
          auto.offset.reset: earliest
          key.deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
          value.deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

server:
  port: ${QUERY_PORT:9411}
  tomcat:
    accesslog:
      enabled: true
      #pattern: %{X-Forwarded-For}i %l %u %t "%r" %s %b %D
      directory: /opt/logs
      prefix: skye-access
      fileDateFormat: .yyyy-MM-dd
  compression:
    enabled: true
    # compresses any response over min-response-size (default is 2KiB)
    # Includes dynamic json content and large static assets from zipkin-ui
    mime-types: application/json,application/javascript,text/css,image/svg

info:
  zipkin:
    version: "@project.version@"

logging:
  level:
    # Silence Invalid method name: '__can__finagle__trace__v3__'
    com.facebook.swift.service.ThriftServiceProcessor: 'OFF'
#     # investigate /api/v1/dependencies
#     zipkin.internal.DependencyLinker: 'DEBUG'
#     # log cassandra queries (DEBUG is without values)
#     com.datastax.driver.core.QueryLogger: 'TRACE'
#     # log cassandra trace propagation
#     com.datastax.driver.core.Message: 'TRACE'
zipkin-extend:
    elasticsearch:
      transport-hosts:
        - 127.0.0.1:9300
      type: zipkin
      cluster-name: skye

spring:
  mvc:
    favicon:
      # zipkin has its own favicon
      enabled: false
  autoconfigure:
    exclude:
      # otherwise we might initialize even when not needed (ex when storage type is cassandra)
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    admin:
      enabled: true
  jedis:
    max-total: 10
    max-idle: 5
    min-idle: 5
    host: zookeeper1.dafy.com
    port: 16389
    test-on-borrow: false
    test-on-return: false
    timeout: 30000

skye.log.server:
  storage:
    type: elasticsearch
    elasticsearch:
      transport-hosts: 127.0.0.1:9300
      index-shards: 3
      index-replicas: 1
      cluster-name: skye
  kafka:
    topic: skye-log
    properties:
      group.id: skye-log
      #kafka 地址
      bootstrap.servers: kafka1.skye.dafy.com:9092
      #zookeeper 地址
      zookeeper.connect: zookeeper1.dafy.com:2181
      #zookeeper 链接超时时间
      zookeeper.connection.timeout.ms: 6000
      #是否自动ack
      enable.auto.commit: false

elasticjob:
  regCenter:
    namespace: elastic-search-index-close
    serverList: zookeeper1.dafy.com:2181
  simpleJob:
    cron: 0 30 0 * * ?
    shardingTotalCount: 1    #最小值为1
    shardingItemParameters:   #不能大于shardingTotalCount
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://10.40.11.40:3306/elasticjobevent?useUnicode=true&characterEncoding=utf-8&verifyServerCertificate=false&useSSL=false&requireSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: dafy
      password: dafy1024
      max-active: 10
      min-idle: 5
      initial-size: 5
      test-on-borrow: true
      validation-query: SELECT 1
  indexOpenDay: 7
  prefix: zipkin:,skye-