skye:
  log:
    storage:
      type: cassandra
    collector:
      kafka:
        topic: skye-log
        groupId: skye-log
        parttion: 4
        properties:
          #kafka 地址
          bootstrap.servers: kafka1.dafy.com:9092
          #zookeeper 地址
          zookeeper.connect: zookeeper1.dafy.com:2181
          #zookeeper 链接超时时间
          zookeeper.connection.timeout.ms: 6000
          #是否自动ack
          enable.auto.commit: false
